/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RankingsScoreRouteImport } from './routes/rankings/score'
import { Route as RankingsPlaysRouteImport } from './routes/rankings/plays'
import { Route as RankingsGlobalRouteImport } from './routes/rankings/global'
import { Route as RankingsCountryRouteImport } from './routes/rankings/country'
import { Route as NewsAdminRouteImport } from './routes/news/admin'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as HelpFaqRouteImport } from './routes/help/faq'
import { Route as CIdRouteImport } from './routes/c/$id'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthDesktopRouteImport } from './routes/auth/desktop'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminSkinsRouteImport } from './routes/admin/skins'
import { Route as AdminNominationRouteImport } from './routes/admin/nomination'
import { Route as AdminBalancingRouteImport } from './routes/admin/balancing'
import { Route as AdminAddonsRouteImport } from './routes/admin/addons'
import { Route as RankingsSkillsSkillRouteImport } from './routes/rankings/skills/$skill'
import { Route as RankingsGradesGradeRouteImport } from './routes/rankings/grades/$grade'

const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsScoreRoute = RankingsScoreRouteImport.update({
  id: '/rankings/score',
  path: '/rankings/score',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsPlaysRoute = RankingsPlaysRouteImport.update({
  id: '/rankings/plays',
  path: '/rankings/plays',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsGlobalRoute = RankingsGlobalRouteImport.update({
  id: '/rankings/global',
  path: '/rankings/global',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsCountryRoute = RankingsCountryRouteImport.update({
  id: '/rankings/country',
  path: '/rankings/country',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsAdminRoute = NewsAdminRouteImport.update({
  id: '/news/admin',
  path: '/news/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpFaqRoute = HelpFaqRouteImport.update({
  id: '/help/faq',
  path: '/help/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDesktopRoute = AuthDesktopRouteImport.update({
  id: '/auth/desktop',
  path: '/auth/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSkinsRoute = AdminSkinsRouteImport.update({
  id: '/admin/skins',
  path: '/admin/skins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNominationRoute = AdminNominationRouteImport.update({
  id: '/admin/nomination',
  path: '/admin/nomination',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBalancingRoute = AdminBalancingRouteImport.update({
  id: '/admin/balancing',
  path: '/admin/balancing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddonsRoute = AdminAddonsRouteImport.update({
  id: '/admin/addons',
  path: '/admin/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsSkillsSkillRoute = RankingsSkillsSkillRouteImport.update({
  id: '/rankings/skills/$skill',
  path: '/rankings/skills/$skill',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsGradesGradeRoute = RankingsGradesGradeRouteImport.update({
  id: '/rankings/grades/$grade',
  path: '/rankings/grades/$grade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/maps': typeof MapsRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/balancing': typeof AdminBalancingRoute
  '/admin/nomination': typeof AdminNominationRoute
  '/admin/skins': typeof AdminSkinsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/desktop': typeof AuthDesktopRoute
  '/auth/error': typeof AuthErrorRoute
  '/c/$id': typeof CIdRoute
  '/help/faq': typeof HelpFaqRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/admin': typeof NewsAdminRoute
  '/rankings/country': typeof RankingsCountryRoute
  '/rankings/global': typeof RankingsGlobalRoute
  '/rankings/plays': typeof RankingsPlaysRoute
  '/rankings/score': typeof RankingsScoreRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/rankings/grades/$grade': typeof RankingsGradesGradeRoute
  '/rankings/skills/$skill': typeof RankingsSkillsSkillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/maps': typeof MapsRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/balancing': typeof AdminBalancingRoute
  '/admin/nomination': typeof AdminNominationRoute
  '/admin/skins': typeof AdminSkinsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/desktop': typeof AuthDesktopRoute
  '/auth/error': typeof AuthErrorRoute
  '/c/$id': typeof CIdRoute
  '/help/faq': typeof HelpFaqRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/admin': typeof NewsAdminRoute
  '/rankings/country': typeof RankingsCountryRoute
  '/rankings/global': typeof RankingsGlobalRoute
  '/rankings/plays': typeof RankingsPlaysRoute
  '/rankings/score': typeof RankingsScoreRoute
  '/admin': typeof AdminIndexRoute
  '/news': typeof NewsIndexRoute
  '/rankings/grades/$grade': typeof RankingsGradesGradeRoute
  '/rankings/skills/$skill': typeof RankingsSkillsSkillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/maps': typeof MapsRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/balancing': typeof AdminBalancingRoute
  '/admin/nomination': typeof AdminNominationRoute
  '/admin/skins': typeof AdminSkinsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/desktop': typeof AuthDesktopRoute
  '/auth/error': typeof AuthErrorRoute
  '/c/$id': typeof CIdRoute
  '/help/faq': typeof HelpFaqRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/admin': typeof NewsAdminRoute
  '/rankings/country': typeof RankingsCountryRoute
  '/rankings/global': typeof RankingsGlobalRoute
  '/rankings/plays': typeof RankingsPlaysRoute
  '/rankings/score': typeof RankingsScoreRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/rankings/grades/$grade': typeof RankingsGradesGradeRoute
  '/rankings/skills/$skill': typeof RankingsSkillsSkillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/login'
    | '/logout'
    | '/maps'
    | '/admin/addons'
    | '/admin/balancing'
    | '/admin/nomination'
    | '/admin/skins'
    | '/auth/callback'
    | '/auth/desktop'
    | '/auth/error'
    | '/c/$id'
    | '/help/faq'
    | '/news/$slug'
    | '/news/admin'
    | '/rankings/country'
    | '/rankings/global'
    | '/rankings/plays'
    | '/rankings/score'
    | '/admin/'
    | '/news/'
    | '/rankings/grades/$grade'
    | '/rankings/skills/$skill'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/login'
    | '/logout'
    | '/maps'
    | '/admin/addons'
    | '/admin/balancing'
    | '/admin/nomination'
    | '/admin/skins'
    | '/auth/callback'
    | '/auth/desktop'
    | '/auth/error'
    | '/c/$id'
    | '/help/faq'
    | '/news/$slug'
    | '/news/admin'
    | '/rankings/country'
    | '/rankings/global'
    | '/rankings/plays'
    | '/rankings/score'
    | '/admin'
    | '/news'
    | '/rankings/grades/$grade'
    | '/rankings/skills/$skill'
  id:
    | '__root__'
    | '/'
    | '/download'
    | '/login'
    | '/logout'
    | '/maps'
    | '/admin/addons'
    | '/admin/balancing'
    | '/admin/nomination'
    | '/admin/skins'
    | '/auth/callback'
    | '/auth/desktop'
    | '/auth/error'
    | '/c/$id'
    | '/help/faq'
    | '/news/$slug'
    | '/news/admin'
    | '/rankings/country'
    | '/rankings/global'
    | '/rankings/plays'
    | '/rankings/score'
    | '/admin/'
    | '/news/'
    | '/rankings/grades/$grade'
    | '/rankings/skills/$skill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MapsRoute: typeof MapsRoute
  AdminAddonsRoute: typeof AdminAddonsRoute
  AdminBalancingRoute: typeof AdminBalancingRoute
  AdminNominationRoute: typeof AdminNominationRoute
  AdminSkinsRoute: typeof AdminSkinsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthDesktopRoute: typeof AuthDesktopRoute
  AuthErrorRoute: typeof AuthErrorRoute
  CIdRoute: typeof CIdRoute
  HelpFaqRoute: typeof HelpFaqRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsAdminRoute: typeof NewsAdminRoute
  RankingsCountryRoute: typeof RankingsCountryRoute
  RankingsGlobalRoute: typeof RankingsGlobalRoute
  RankingsPlaysRoute: typeof RankingsPlaysRoute
  RankingsScoreRoute: typeof RankingsScoreRoute
  AdminIndexRoute: typeof AdminIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  RankingsGradesGradeRoute: typeof RankingsGradesGradeRoute
  RankingsSkillsSkillRoute: typeof RankingsSkillsSkillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/score': {
      id: '/rankings/score'
      path: '/rankings/score'
      fullPath: '/rankings/score'
      preLoaderRoute: typeof RankingsScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/plays': {
      id: '/rankings/plays'
      path: '/rankings/plays'
      fullPath: '/rankings/plays'
      preLoaderRoute: typeof RankingsPlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/global': {
      id: '/rankings/global'
      path: '/rankings/global'
      fullPath: '/rankings/global'
      preLoaderRoute: typeof RankingsGlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/country': {
      id: '/rankings/country'
      path: '/rankings/country'
      fullPath: '/rankings/country'
      preLoaderRoute: typeof RankingsCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/admin': {
      id: '/news/admin'
      path: '/news/admin'
      fullPath: '/news/admin'
      preLoaderRoute: typeof NewsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/faq': {
      id: '/help/faq'
      path: '/help/faq'
      fullPath: '/help/faq'
      preLoaderRoute: typeof HelpFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/desktop': {
      id: '/auth/desktop'
      path: '/auth/desktop'
      fullPath: '/auth/desktop'
      preLoaderRoute: typeof AuthDesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/skins': {
      id: '/admin/skins'
      path: '/admin/skins'
      fullPath: '/admin/skins'
      preLoaderRoute: typeof AdminSkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nomination': {
      id: '/admin/nomination'
      path: '/admin/nomination'
      fullPath: '/admin/nomination'
      preLoaderRoute: typeof AdminNominationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/balancing': {
      id: '/admin/balancing'
      path: '/admin/balancing'
      fullPath: '/admin/balancing'
      preLoaderRoute: typeof AdminBalancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/addons': {
      id: '/admin/addons'
      path: '/admin/addons'
      fullPath: '/admin/addons'
      preLoaderRoute: typeof AdminAddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/skills/$skill': {
      id: '/rankings/skills/$skill'
      path: '/rankings/skills/$skill'
      fullPath: '/rankings/skills/$skill'
      preLoaderRoute: typeof RankingsSkillsSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/grades/$grade': {
      id: '/rankings/grades/$grade'
      path: '/rankings/grades/$grade'
      fullPath: '/rankings/grades/$grade'
      preLoaderRoute: typeof RankingsGradesGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MapsRoute: MapsRoute,
  AdminAddonsRoute: AdminAddonsRoute,
  AdminBalancingRoute: AdminBalancingRoute,
  AdminNominationRoute: AdminNominationRoute,
  AdminSkinsRoute: AdminSkinsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthDesktopRoute: AuthDesktopRoute,
  AuthErrorRoute: AuthErrorRoute,
  CIdRoute: CIdRoute,
  HelpFaqRoute: HelpFaqRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsAdminRoute: NewsAdminRoute,
  RankingsCountryRoute: RankingsCountryRoute,
  RankingsGlobalRoute: RankingsGlobalRoute,
  RankingsPlaysRoute: RankingsPlaysRoute,
  RankingsScoreRoute: RankingsScoreRoute,
  AdminIndexRoute: AdminIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  RankingsGradesGradeRoute: RankingsGradesGradeRoute,
  RankingsSkillsSkillRoute: RankingsSkillsSkillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
