import { mapped, type ValueIn } from './helpers/mapped.js';
import { defineMessages } from './i18n/translate.js';
import type { FixedLength } from './types/fixed_length.js';

export const Skills = [
	'accuracy',
	'speed',
	'stamina',
	'jackspeed',
	'coordination',
	'release',
	'reading',
	'consistency',
	'concentration',
	'speedjam',
	'memory',
] as const;
export const SKILL = mapped(Skills);
export type SkillName = ValueIn<typeof SKILL>;

export const UPGRADE = defineMessages({
	[SKILL.accuracy]: [
		'Dell XPS chiclet keyboard',
		'Lenovo IdeaPad ultrabook chiclet keyboard',
		'Unbranded membrane keyboard',
		'Logitech K120',
		'Cooler Master MS110',
		'Corsair K60',
		'Ducky One 2 Mini',
		'Glorious GMMK Pro',
		'Steelseries Apex Pro',
		'IRON165',
		'Norbaforce Mark IV',
	],
	[SKILL.speed]: [
		16,
		18,
		20,
		22,
		24,
		26,
		28,
		30,
		32,
		34,
		36,
	],
	[SKILL.stamina]: [
		'No warmup',
		'Thinks about warmup',
		'Warmup on easy maps',
		'Warmup on normal maps',
		'Warmup on hard maps',
		'Warmup on stamina packs',
		'1 hour pre-session warmup',
		'30 minutes muscle strength warmup',
		'2 hours gym session',
		'Gym, stretch session + meditation',
		'Mid-play stretching + meditation',
	],
	[SKILL.jackspeed]: [
		"Synaptics drivers",
		"60hz GMMK firmware",
		"Outdated stock Windows drivers",
		"Latest stock Windows drivers",
		"Stock Logitech G Hub",
		"Optimized MasterPlus+",
		"Low latency Corsair iCUE",
		"Embedded keyboard firmware",
		"Steelseries GG embedded profile",
		"Modded rapid trigger firmware",
		"Modded actuation prediction firmware",
	],
	[SKILL.coordination]: [
		"Controller",
		"DFJK",
		"SDKL",
		"ASL:",
		"AS:\"",
		"QWOP",
		"QWP{",
		"QW{}",
		"AS45",
		"AS56",
		"←↓↑→",
	],
	[SKILL.release]: [
		"Default skin LNs",
		"Arrow skin LNs",
		"Circle skin LNs",
		"Bar skin LNs",
		"No tail LNs",
		"Fade-out tail LNs",
		"Light percy LNs",
		"Cut percy LNs",
		"Cut percy with LN end indicator",
		"Blank LN body with bar LN tail",
		"BottomCentered Anchored LN tails",
	],
	[SKILL.reading]: [
		30,
		50,
		60,
		75,
		100,
		120,
		144,
		165,
		240,
		360,
		540,
	],
	[SKILL.consistency]: [
		"Stool",
		"Basic plastic chair",
		"Metal folding chair",
		"Wooden chair",
		"Amazon basics Puresoft office chair",
		"CENTERHALV Ikea mesh office chair",
		"Hbada E3 Pro",
		"AndaSeat Kaiser 3",
		"DXRacer Drifting",
		"Secretlab TITAN Evo",
		"DOF Reality H6R",
	],
	[SKILL.concentration]: [
		'Sizzling speakers',
		'Used earbuds',
		'AirPods',
		'Yealink Phone Headset',
		'Logitech H390',
		'Razer BlackShark V3',
		'Voyager Focus 2',
		'Steelseries Arctis Nova 5',
		'Sony WH-1000XM4',
		'Sennheiser Momentum 4',
		'Bose QuietComfort Ultra',
	],
	[SKILL.speedjam]: [
		'Default skin notes',
		"Diamond skin notes",
		"Arrow skin notes",
		"Circle skin notes",
		"Bar skin notes",
		"Per-map scroll speed setting",
		"Music anticipation",
		"Note snap coloring",
		"Audio focused accuracy",
		"Dynamic sight focus",
		"Cap",
	],
	[SKILL.memory]: [
		"Vibe playing",
		"Passive learning",
		"Bruteforce learning",
		"Map editor studying",
		"Split map sections training",
		"Post-it notes",
		"Post-it pattern drawings",
		"Re-mapping to get mapper's advantage",
		"Memorizing the whole map",
		"Mental SV palace",
		"Dualscreen",
	]
} satisfies Record<SkillName, FixedLength<(string | number), 11>>);

/** The "pressure" skills whose strained notes train consistency: playing
 *  through speed-family pressure without choking is what consistency rewards. */
export const PRESSURE_SKILLS: Set<SkillName> = new Set([SKILL.speed, SKILL.stamina, SKILL.jackspeed, SKILL.coordination, SKILL.reading, SKILL.speedjam]);

const MINDBLOCK_EXEMPT = new Set<SkillName>([SKILL.stamina, SKILL.memory, SKILL.speed, SKILL.jackspeed]);
export const MINDBLOCK_SKILLS: SkillName[] = Skills.filter(s => !MINDBLOCK_EXEMPT.has(s));